### ISSUE TITLE
Resource plan

### ISSUE THREAD

**Issue by orthecreedence** [basisproject/tracker#58]
When members complete work, they get [credits](#53) in exchange (yes, exchange, sorry Marx). This is fine for a labor-based economy, but once the system starts [tracking resources](#31) then the members need a way to pay for the costs of the resources.

The loose idea here is that each product has a resource content for each tracked resource, and that resource content has a standard unit (like grams for iron, liters for crude oil, etc). Now for each tracked resource, we effectively set a per-unit price that is added to the final price of every product.

For instance, if a chair had 15₡ (credits) worth of labor imbued in it, but also used 3kg wood and 4g steel, then the *base cost* as a price is 15₡, but we need to price in the resources too: wood might be 0.006₡/g and steel 0.04₡/g. Our target price if someone were to buy the chair in-network is now `15 + (3000 * 0.006) + (4 * 0.04) = 33.16`.

So the resource plan is the ability to set a per-unit price (in credits ₡) on each tracked resource.

Notes:

- Need to think about voting models here. We can't allow arbitrary values, because someone could enter a price of 99999999999999999999 for fossil fuels and screw everyone's day up.
  - Thinking some kind of +/- "adjustment" vote that happens every day or so. In other words, you basically just vote whether a resource should go up, down, or don't care and the system registers this and adjusts the price based on the average of all votes.
- Would be interesting to allow per-region resource pricing as well.
  - For instance, a region might want to set a higher price on wood from their old growth redwood forest. This resource would still be considered "wood" and would be subject to the global wood price, but maybe each specific *source* of wood can have its own price set by the people who manage that resource.
  - On the flip side a region might want to set a price on a resource being *consumed* in their area. This would be really useful for things like rationing water during a drought and gives communities ways to manage resources locally.

**Comment by Patrick-T-Anderson** [comment]
> When members complete work, they get [credits](#53) in exchange

Would it be ok if some of the credits represent fractional ownership in land (real estate)?
Members gain control as they gain ownership, and pay only the real costs of production.

**Comment by orthecreedence** [comment]
So as it's modeled now, participants are all fractional owners of *all* the property that's owned by the network. Basis itself is set up to be more of a large-scale productive network system that mediates exchanges across many properties rather than a tool used for managing a single piece of real property. The idea is that over time the participants all collectively enjoy the benefits of that shared ownership (no rent, on a large or massive scale).

That said, there are mechanisms for work (measured in labor hours) representing a larger share of *control* (or even *ownership*) of that collective property: #91.

**Comment by orthecreedence** [comment]
Closing in favor of #17
